In [1]:
import numpy as np

In [2]:
arr= np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [3]:
ar= np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
x= np.array([7,8,9],dtype=float)
print(x , type(x))

[7. 8. 9.] <class 'numpy.ndarray'>


In [5]:
y=np.zeros(6)
print(y)

[0. 0. 0. 0. 0. 0.]


In [6]:
z=np.ones((3,2),dtype=int)
print(z)

[[1 1]
 [1 1]
 [1 1]]


In [7]:
a=np.empty((2,3))
print(a)
'''why we use np.empty() over np.zeros()
because This can be useful when we want to create an array and fill it with values later, 
without the overhead of initializing it to zero first.'''

[[0. 0. 0.]
 [0. 0. 0.]]


'why we use np.empty() over np.zeros()\nbecause This can be useful when we want to create an array and fill it with values later, \nwithout the overhead of initializing it to zero first.'

In [8]:
b=np.arange(0,20,2)
print(b)

[ 0  2  4  6  8 10 12 14 16 18]


In [9]:
c=np.linspace(0,1,6)
print(c)
'''in arange they will exclude the last number but in linspace they will include the last number'''

[0.  0.2 0.4 0.6 0.8 1. ]


'in arange they will exclude the last number but in linspace they will include the last number'

In [10]:
d=np.random.random((3,3))
print(d)

[[0.96419686 0.87181987 0.03557386]
 [0.13613272 0.01834496 0.9163577 ]
 [0.4958011  0.22636442 0.79098847]]
