In [3]:
import numpy as np

In [ ]:
#8.	Create a 1-D NumPy array of the integers 1 to 20. Print its ndim, shape, size, and dtype.
a=np.linspace(1,20,20,dtype=int)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
1
20
int32


In [34]:
#9.	Create a 4x5 array of random integers between 0 and 50 (use np.random.seed(0) first for reproducibility). Print the array, then print arr.itemsize and arr.nbytes.
np.random.seed(0)
a = np.random.randint(0, 50, (4, 5))
print(a)
print(a.itemsize)
print(a.nbytes)

[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]
4
80


In [35]:
#10.	Given arr = np.arange(1, 13).reshape(3, 4), write code to: (a) print the element in row 2, column 3, (b) print the last row using negative indexing, (c) print the last column.
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print(arr[1, 2])
print(arr[-1])
print(arr[:, -1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[ 9 10 11 12]
[ 4  8 12]


In [36]:
#11.	Given the same 3x4 array, extract: (a) the first two rows and first two columns as a subarray, (b) every alternate column, (c) the array with columns reversed.
print(arr[:2, :2])
print(arr[:, ::2])
print(arr[:, ::-1])

[[1 2]
 [5 6]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [37]:
#Create a 6x4 array. Use np.hsplit() to split it into two 6x2 arrays, and np.vsplit() to split it into two 3x4 arrays.
np.random.seed(0)
i=np.random.randint(0,50,(6,4))
print(i)
j=np.hsplit(i,2)
print(j)
k=np.vsplit(i,2)
print(k)

[[44 47  0  3]
 [ 3 39  9 19]
 [21 36 23  6]
 [24 24 12  1]
 [38 39 23 46]
 [24 17 37 25]]
[array([[44, 47],
       [ 3, 39],
       [21, 36],
       [24, 24],
       [38, 39],
       [24, 17]]), array([[ 0,  3],
       [ 9, 19],
       [23,  6],
       [12,  1],
       [23, 46],
       [37, 25]])]
[array([[44, 47,  0,  3],
       [ 3, 39,  9, 19],
       [21, 36, 23,  6]]), array([[24, 24, 12,  1],
       [38, 39, 23, 46],
       [24, 17, 37, 25]])]


In [24]:
#12.	Create a 3x4 subarray view from a larger array, modify one of its elements, and print the original array to demonstrate that slicing returns a view, not a copy. Then repeat using .copy() and show that the original is unaffected.
x = np.random.randint(0, 10, (5, 6))
subarray = x[:3, :4]
subarray[0, 0] = 99
print("Original array after modifying subarray:")
print(x)

# Using .copy()
subarray_copy = x[:3, :4].copy()
subarray_copy[0, 0] = 88
print("Original array after modifying subarray copy:")
print(x)

Original array after modifying subarray:
[[99  0  0  4  5  5]
 [ 6  8  4  1  4  9]
 [ 8  1  1  7  9  9]
 [ 3  6  7  2  0  3]
 [ 5  9  4  4  6  4]]
Original array after modifying subarray copy:
[[99  0  0  4  5  5]
 [ 6  8  4  1  4  9]
 [ 8  1  1  7  9  9]
 [ 3  6  7  2  0  3]
 [ 5  9  4  4  6  4]]


In [26]:
# 15.	Create a 1-D array of 15 elements. Use np.split() to split it into three equal parts, and print each part.
arr=np.arange(15)
print(arr)
a1,a2,a3=np.split(arr,[5,10])
print(a1)
print(a2)
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [28]:
a=np.arange(6).reshape((2,3))
b=np.arange(6,12).reshape((2,3))
print(a)
print(b)
ab=np.vstack((a,b))
ba=np.concatenate((a,b),axis=0)
print(ab)
print(ba)
cd=np.hstack((a,b))
dc=np.concatenate((a,b),axis=1)
print(cd)
print(dc)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [38]:
#12.	Create a 3x4 subarray view from a larger array, modify one of its elements, and print the original array to demonstrate that slicing returns a view, not a copy. Then repeat using .copy() and show that the original is unaffected.
y = np.arange(12).reshape(4, 3)
subarray = y[1:4, 0:3]
print("Original array:")
print(y)
subarray[0, 0] = 99
print("Modified subarray:")
print(subarray)
print("Original array after modifying subarray:")
print(y)

y = np.arange(12).reshape(4, 3)
subarray = y[1:4, 0:3].copy()
print("Original array:")
print(y)
subarray[0, 0] = 99
print("Modified subarray:")
print(subarray)
print("Original array after modifying subarray:")
print(y)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Modified subarray:
[[99  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Original array after modifying subarray:
[[ 0  1  2]
 [99  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Modified subarray:
[[99  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Original array after modifying subarray:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [39]:
#13.	Create a 1-D array of 12 elements and reshape it into a 3x4 matrix. Then reshape the same original array into a column vector using both reshape((12,1)) and x[:, np.newaxis], and confirm the two results are identical.
x = np.arange(12)
y = x.reshape(3, 4)
z1 = x.reshape((12, 1))
z2 = x[:, np.newaxis]
print("Original array:")
print(x)
print("Reshaped into 3x4 matrix:")
print(y)
print("Column vector using reshape((12, 1)):")
print(z1)
print("Column vector using x[:, np.newaxis]:")
print(z2)
print("Are the two column vectors identical?")
print(np.array_equal(z1, z2))

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped into 3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Column vector using reshape((12, 1)):
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
Column vector using x[:, np.newaxis]:
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
Are the two column vectors identical?
True
