In [2]:
import numpy as np

In [4]:
np.random.seed(0)
a= np.random.randint(10, size=10)
print(a)
np.sort(a)

[5 0 3 3 7 9 3 5 2 4]


array([0, 2, 3, 3, 3, 4, 5, 5, 7, 9])

In [5]:
np.argsort(a)

array([1, 8, 2, 3, 6, 9, 0, 7, 4, 5], dtype=int64)

In [6]:
np.random.seed(0)
b=np.random.randint(0,50,(4,6))
print(b)
bc=np.sort(b, axis=0)
print(bc)
br=np.sort(b,axis=1)
print(br)

[[44 47  0  3  3 39]
 [ 9 19 21 36 23  6]
 [24 24 12  1 38 39]
 [23 46 24 17 37 25]]
[[ 9 19  0  1  3  6]
 [23 24 12  3 23 25]
 [24 46 21 17 37 39]
 [44 47 24 36 38 39]]
[[ 0  3  3 39 44 47]
 [ 6  9 19 21 23 36]
 [ 1 12 24 24 38 39]
 [17 23 24 25 37 46]]


In [7]:
np.random.seed(0)
c=np.random.randint(0,50, size=15)
print(c)
ca=np.partition(c,4)
print(ca)
np.sort(c)

[44 47  0  3  3 39  9 19 21 36 23  6 24 24 12]
[ 3  0  3  6  9 12 19 47 21 36 23 39 24 24 44]


array([ 0,  3,  3,  6,  9, 12, 19, 21, 23, 24, 24, 36, 39, 44, 47])

In [15]:
student_names = np.array(["Anobe", "Bob", "Charle", "David"])
scores = np.array([82, 65, 91, 74])
sort=np.argsort(scores)
for i in sort:
    print(student_names[i])

Bob
David
Anobe
Charle


In [18]:
np.random.seed(0)
X = np.random.rand(10, 2)

dist_sq = np.sum((X[:, np.newaxis, :] - X[np.newaxis, :, :]) ** 2, axis=-1)
nearest_neighbors = np.argsort(dist_sq, axis=1)[:, 1:3]

for point_index, neighbors in enumerate(nearest_neighbors):
    print(f"Point {point_index}: {neighbors}")

Point 0: [2 1]
Point 1: [0 5]
Point 2: [0 1]
Point 3: [6 0]
Point 4: [5 1]
Point 5: [1 4]
Point 6: [3 0]
Point 7: [2 1]
Point 8: [3 2]
Point 9: [6 0]


In [30]:
name=['Alice', 'Bob', 'Charlie', 'David']
age=[22,29,30,37]
marks=[85.6, 92.3, 78.9, 88.5]

data=np.zeros(4, dtype=[('name', 'U10'), ('age', 'i4'), ('marks', 'f8')])
data['name'] = name
data['age'] = age
data['marks'] = marks
print(data[data['age'] < 30]['name'])

['Alice' 'Bob']


In [42]:
title=['DSA','EDA','ML','AI']
author=['Alice','Bob','Charlie','David']
price=[229.99, 359.99, 429.99, 159.99]

book=np.zeros(4, dtype=[('title', 'U10'), ('author', 'U10'), ('price', 'f8')])
book['title'] = title
book['author'] = author
book['price'] = price
print(book)

[('DSA', 'Alice', 229.99) ('EDA', 'Bob', 359.99) ('ML', 'Charlie', 429.99)
 ('AI', 'David', 159.99)]


In [44]:
print(book['title'])
print(book[1])
print(book[book['price'] < 300]['title'])


['DSA' 'EDA' 'ML' 'AI']
('EDA', 'Bob', 359.99)
['DSA' 'AI']


In [45]:
#25.	Define the same compound dtype using both the dictionary form ({'names':..., 'formats':...}) and the list-of-tuples form ([('title','U30'), ...]), and confirm both produce an equivalent dtype.
dtype_dict = {'names': ['title', 'author', 'price'], 'formats': ['U30', 'U20', 'f8']}
dtype_list = [('title', 'U30'), ('author', 'U20'), ('price', 'f8')]
print(np.dtype(dtype_dict) == np.dtype(dtype_list))

True
