In [1]:
import numpy as np

In [6]:
name=['Alice','Bob','Charlie','David']
age=[24,45,37,19]
weight=[55.0,85.3,72.1,68.4]

In [38]:
data=np.zeros(
    4,
        dtype={
        'names':('name','age','weight'),
        'formats':('U10','i4','f8')
    }
)

In [30]:
print("Structured array using a compound data type")
print(data.dtype)

Structured array using a compound data type
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [31]:
data['name']=name
data['age']=age
data['weight']=weight

In [32]:
print("filled structured array")
print(data)


filled structured array
[('Alice', 24, 55. ) ('Bob', 45, 85.3) ('Charlie', 37, 72.1)
 ('David', 19, 68.4)]


In [33]:

print("all names")
print(data['name'])



all names
['Alice' 'Bob' 'Charlie' 'David']


In [34]:
print("first row of data")
print(data[0])



first row of data
('Alice', 24, 55.)


In [35]:
print("names from the last row")
print(data[-1]['name'])


names from the last row
David


In [36]:

print("names where age is under 30")
print(data[data['age'] < 30]['name'])


names where age is under 30
['Alice' 'David']


In [15]:

#dictonary method
np.dtype({
    'names':('name','age','weight'),
    'formats':('U10','i4','f8')
})


dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [16]:

np.dtype({
    'names':('name','age','weight'),
    'formats':((np.str_,10),int,np.float32)
})


dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [17]:

np.dtype([
    ('name','S10'),
    ('age','i4'),
    ('weight','f8')
])



dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [18]:

np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [25]:
tp=np.dtype([
    ('id','i8'),
    ('mat','f8',(3,3))
])



In [26]:
x=np.zeros(1,dtype=tp)

In [27]:
print(x[0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])


In [28]:
print(x['mat'][0])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
#record array

data_rec=data.view(np.recarray)
print(data_rec.age)

[0 0 0 0]


In [40]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

265 ns ± 55.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
3.28 μs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
6.94 μs ± 208 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
